var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { cardTableTheme } from '../../theme/core/cardTable';
export var StyledTh = styled.th(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n   padding: 0.5rem;\n"], ["\n   padding: 0.5rem;\n"])));
export var StyledTr = styled.tr(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: flex;\n    justify-content: space-between;\n    /* align-content: start; */\n    align-items: center;\n    /* justify-items: left; */\n    margin-bottom: 1rem;\n    width: 100%;\n    padding: 0.5rem 1rem 0.5rem 1rem;\n    background-color: transparentize( white,0.15 );\n    border: 1px solid ", ";\n    border-radius: 5px;\n"], ["\n    display: flex;\n    justify-content: space-between;\n    /* align-content: start; */\n    align-items: center;\n    /* justify-items: left; */\n    margin-bottom: 1rem;\n    width: 100%;\n    padding: 0.5rem 1rem 0.5rem 1rem;\n    background-color: transparentize( white,0.15 );\n    border: 1px solid ", ";\n    border-radius: 5px;\n"])), function (pr) { return pr.borderColor || cardTableTheme.defaults.borderColor; });
export var StyledThead = styled.thead(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    ", "{\n        background-color:", ";\n    }\n"], ["\n    ", "{\n        background-color:", ";\n    }\n"])), StyledTr, function (pr) { return pr.headerBgColor || cardTableTheme.defaults.headerBgColor; });
export var StyledTbody = styled.tbody(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    ", "{\n        box-shadow: 0px 4px 4px rgba(0, 74, 215, 0.45);\n        background-color:", ";\n        &:nth-child(even){background-color: ", ";};\n        ", "\n    }\n"], ["\n    ", "{\n        box-shadow: 0px 4px 4px rgba(0, 74, 215, 0.45);\n        background-color:", ";\n        &:nth-child(even){background-color: ", ";};\n        ",
    "\n    }\n"])), StyledTr, function (pr) { return pr.trBgColor || cardTableTheme.defaults.trBgColor; }, function (pr) { return pr.nthTrBgColor || cardTableTheme.defaults.nthTrBgColor; }, function (pr) { return pr.hoverEffect ? "&:hover {box-shadow: 0px 4px 19px " + (pr.hoverShadowColor || cardTableTheme.defaults.hoverShadowColor) + ";\n                                border:1px solid " + (pr.hoverBorderColor || cardTableTheme.defaults.hoverBorderColor) + ";\n                                background-color:" + (pr.hoverTrBgColor || cardTableTheme.defaults.hoverTrBgColor) + ";}" : ''; });
export var StyledTd = styled.td(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    display: inline-block;\n    padding: 0.5rem;\n    text-align: left;\n"], ["\n    display: inline-block;\n    padding: 0.5rem;\n    text-align: left;\n"])));
export var StyledTable = styled.table(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    width:90%;\n    margin:auto;\n    ", ",", "{\n        ", "\n        text-align: left;\n    }\n"], ["\n    width:90%;\n    margin:auto;\n    ", ",", "{\n        ", "\n        text-align: left;\n    }\n"])), StyledTd, StyledTh, function (pr) { var _a; return pr.thData && "width:" + 100 / ((_a = pr.thData) === null || _a === void 0 ? void 0 : _a.length) + "%;"; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
