var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { fileInputTheme } from '../../theme/core/fileInput';
import { textTheme } from '../../theme/core/text';
import { defaultTheme } from '../../theme/theme';
export var StyledInput = styled.input(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    position: absolute;\n    left: 134px;\n    top: -60px;\n    cursor: pointer;\n    opacity: 0;\n    -moz-opacity: 0;\n    filter: progid:DXImageTransform.Microsoft.Alpha(opacity = 0);\n"], ["\n    position: absolute;\n    left: 134px;\n    top: -60px;\n    cursor: pointer;\n    opacity: 0;\n    -moz-opacity: 0;\n    filter: progid:DXImageTransform.Microsoft.Alpha(opacity = 0);\n"])));
export var FileNameSpan = styled.span(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    width:70%;\n    margin: 1px 1px 1px 5px;\n    font-size: ", ";\n    color: ", ";\n    background:transparent;\n    font-style: italic;\n    padding: .3em .6em;\n    white-space: nowrap;\n    overflow: hidden !important;\n    text-overflow: ellipsis;\n"], ["\n    width:70%;\n    margin: 1px 1px 1px 5px;\n    font-size: ", ";\n    color: ", ";\n    background:transparent;\n    font-style: italic;\n    padding: .3em .6em;\n    white-space: nowrap;\n    overflow: hidden !important;\n    text-overflow: ellipsis;\n"])), function (pr) { return pr.size && textTheme.sizes[pr.size].fontSize; }, function (pr) { return pr.textColor || fileInputTheme.defaults.textColor; });
export var BrowsSpan = styled.span(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    width:30%;\n    text-align:center;\n    border: none;\n    background: ", ";\n    color: ", ";\n    font-weight: bold;\n    padding: .3em .6em;\n    -webkit-text-decoration: none;\n    font-size: ", ";\n    -moz-border-radius: 5px;\n    -webkit-border-radius: 5px;\n    border-radius: 5px;\n"], ["\n    width:30%;\n    text-align:center;\n    border: none;\n    background: ", ";\n    color: ", ";\n    font-weight: bold;\n    padding: .3em .6em;\n    -webkit-text-decoration: none;\n    font-size: ", ";\n    -moz-border-radius: 5px;\n    -webkit-border-radius: 5px;\n    border-radius: 5px;\n"])), function (pr) { return pr.btnBgColor || fileInputTheme.defaults.btnBgColor; }, function (pr) { return pr.btnTextColor || fileInputTheme.defaults.btnTextColor; }, function (pr) { return pr.size && textTheme.sizes[pr.size].fontSize; });
export var StyledLabel = styled.label(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    ", ";\n    display:inline-flex;\n    border: 1px solid ", ";\n    cursor: pointer;\n    justify-content:flex-end;\n    flex-direction:row-reverse;\n    border-radius:5px;\n    -moz-border-radius: 5px;\n    -webkit-border-radius: 5px;\n    ", ";\n"], ["\n    ", ";\n    display:inline-flex;\n    border: 1px solid ", ";\n    cursor: pointer;\n    justify-content:flex-end;\n    flex-direction:row-reverse;\n    border-radius:5px;\n    -moz-border-radius: 5px;\n    -webkit-border-radius: 5px;\n    ",
    ";\n"])), function (pr) { return pr.disabled === true ? 'pointer-events: none;opacity: 0.4;' : ''; }, function (pr) { return pr.hasError || pr.errorText !== '' ? defaultTheme.dangerColor : pr.borderColor || fileInputTheme.defaults.borderColor; }, function (pr) { return pr.hoverEffect ? "&:hover{\n        " + BrowsSpan + "{\n                border:1px solid " + (pr.btnHoverBorderColor || fileInputTheme.defaults.btnHoverBorderColor) + ";\n                background: " + (pr.btnHoverBgColor || fileInputTheme.defaults.btnHoverBgColor) + ";\n            }\n    }" : ''; });
export var StyledWrapper = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    display:flex;\n    flex-direction:column;\n    width:280px;\n"], ["\n    display:flex;\n    flex-direction:column;\n    width:280px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
