var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { defaultTheme } from '../../theme';
export var StyledLogo = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    grid-area: logo;\n    height: 70px;\n    margin-left:30px;\n    img{\n        width:inherit;\n        height:inherit;\n    }\n"], ["\n    grid-area: logo;\n    height: 70px;\n    margin-left:30px;\n    img{\n        width:inherit;\n        height:inherit;\n    }\n"])));
export var StyledNav = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: grid;\n    grid-area: nav;\n    margin-right:30px;\n    grid-template-columns: repeat(", ", auto);\n    align-items: center;\n    justify-items: end;\n    div{\n        transition: 0.5s;\n        &:hover {\n                transform: scale(1.1);\n        }\n    }\n"], ["\n    display: grid;\n    grid-area: nav;\n    margin-right:30px;\n    grid-template-columns: repeat(", ", auto);\n    align-items: center;\n    justify-items: end;\n    div{\n        transition: 0.5s;\n        &:hover {\n                transform: scale(1.1);\n        }\n    }\n"])), function (pr) { var _a; return (_a = pr.navOptions) === null || _a === void 0 ? void 0 : _a.length; });
export var NavButton = styled.button(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    color:#fff;\n    display: none;\n    grid-area: burger;\n    margin-right:30px;\n    padding: 0;\n    justify-self: end;\n    align-self: center;\n    font-size: 40px;\n    border: none;\n    background: none;\n    outline: none;\n    transition: 0.1s;\n    &:active {\n        transform: scale(1.2);\n    }\n"], ["\n    color:#fff;\n    display: none;\n    grid-area: burger;\n    margin-right:30px;\n    padding: 0;\n    justify-self: end;\n    align-self: center;\n    font-size: 40px;\n    border: none;\n    background: none;\n    outline: none;\n    transition: 0.1s;\n    &:active {\n        transform: scale(1.2);\n    }\n"])));
export var StyledHeader = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    position: fixed;\n    top: 0; /* Stick it to the top */\n    left:0;\n    min-height: 50px;\n    width: 100%;\n    z-index:100000;\n    display: grid;\n    align-items:center;\n    grid-template-areas: \"logo nav\";\n\n    /* Cosmetics */\n    background-color: ", ";\n    box-shadow: 0 4px 8px 0 ", ";\n\n    @media (max-width: 700px){\n        grid-template-areas: \"logo burger\" \"nav nav\";\n        ", " {\n            grid-template-rows: repeat(4, auto);\n            grid-template-columns: none;\n            justify-items:center;\n            width:100%;\n            grid-row-gap: 20px;\n            margin: 0;\n            padding: 30px 0 30px;\n            background:", ";\n            box-shadow: 0 4px 8px 0 ", ";\n            border-bottom-left-radius: 10px;\n            border-bottom-right-radius: 10px;\n        }\n        ", " {\n            display: inline;\n        }\n    }\n"], ["\n    position: fixed;\n    top: 0; /* Stick it to the top */\n    left:0;\n    min-height: 50px;\n    width: 100%;\n    z-index:100000;\n    display: grid;\n    align-items:center;\n    grid-template-areas: \"logo nav\";\n\n    /* Cosmetics */\n    background-color: ", ";\n    box-shadow: 0 4px 8px 0 ", ";\n\n    @media (max-width: 700px){\n        grid-template-areas: \"logo burger\" \"nav nav\";\n        ", " {\n            grid-template-rows: repeat(4, auto);\n            grid-template-columns: none;\n            justify-items:center;\n            width:100%;\n            grid-row-gap: 20px;\n            margin: 0;\n            padding: 30px 0 30px;\n            background:", ";\n            box-shadow: 0 4px 8px 0 ", ";\n            border-bottom-left-radius: 10px;\n            border-bottom-right-radius: 10px;\n        }\n        ", " {\n            display: inline;\n        }\n    }\n"])), function (pr) { return pr.bgColor || pr.theme.navbar.defaults.bgColor; }, function (pr) { return pr.shadowColor || pr.theme.navbar.defaults.shadowColor; }, StyledNav, function (pr) { return pr.popBgColor || pr.theme.navbar.defaults.popBgColor; }, function (pr) { return pr.popShadowColor || pr.theme.navbar.defaults.popShadowColor; }, NavButton);
StyledHeader.defaultProps = {
    theme: defaultTheme
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
