var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { defaultTheme } from '../../theme';
export var StyledLogo = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    grid-area: logo;\n    height: 70px;\n    text-align:center;\n    margin:auto;\n    img{\n        vertical-align:middle;\n        width:inherit;\n        height:inherit;\n    }\n    hr{\n        border: 1px solid ", "rgb(221, 221, 221);\n    }\n"], ["\n    grid-area: logo;\n    height: 70px;\n    text-align:center;\n    margin:auto;\n    img{\n        vertical-align:middle;\n        width:inherit;\n        height:inherit;\n    }\n    hr{\n        border: 1px solid ", "rgb(221, 221, 221);\n    }\n"])), function (pr) { return pr.hrColor || pr.theme.sidebar.defaults.hrColor; });
StyledLogo.defaultProps = {
    theme: defaultTheme
};
export var StyledNav = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    margin: 50px auto;\n    display: flex;\n    flex-direction: column;\n\n    > a {\n        font-size: 1.5rem;\n        text-decoration: none;\n        padding: 0.5rem 1rem;\n        border: 1px solid silver;\n        margin-bottom: 0.5rem;\n        border-radius: 1rem;\n        text-align:center;\n        transition: 0.5s;\n        &:hover {\n            transform: scale(1.1);\n        }\n    }\n"], ["\n    margin: 50px auto;\n    display: flex;\n    flex-direction: column;\n\n    > a {\n        font-size: 1.5rem;\n        text-decoration: none;\n        padding: 0.5rem 1rem;\n        border: 1px solid silver;\n        margin-bottom: 0.5rem;\n        border-radius: 1rem;\n        text-align:center;\n        transition: 0.5s;\n        &:hover {\n            transform: scale(1.1);\n        }\n    }\n"])));
export var Wrapper = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n\ttransition: margin 0.3s;\n    .open,\n    .close {\n        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);\n        border-radius: 1rem;\n        font-size: 1.5rem;\n        background: white;\n        text-transform: uppercase;\n        text-decoration: none;\n        display: inline-flex;\n        flex-direction: row;\n        align-items: center;\n        padding: 0.5rem 1rem;\n        border: 1px solid silver;\n        > svg {\n            margin-right: 1rem;\n        }\n    }\n\n"], ["\n\ttransition: margin 0.3s;\n    .open,\n    .close {\n        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);\n        border-radius: 1rem;\n        font-size: 1.5rem;\n        background: white;\n        text-transform: uppercase;\n        text-decoration: none;\n        display: inline-flex;\n        flex-direction: row;\n        align-items: center;\n        padding: 0.5rem 1rem;\n        border: 1px solid silver;\n        > svg {\n            margin-right: 1rem;\n        }\n    }\n\n"])));
export var StyledContent = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    width: 90%;\n    margin:auto;\n"], ["\n    width: 90%;\n    margin:auto;\n"])));
export var StyledHeader = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    padding: 1rem;\n\tbox-sizing: border-box;\n\tbackground: ", ";\n\tposition: fixed;\n\ttop: 0;\n\tleft: 0;\n\theight: 100%;\n\twidth: 300px;\n\ttransform: translatex(-100%);\n\ttransition: transform 0.3s;\n\tbox-shadow: 0 1px 8px 0 ", ";\n\n\t&:target {\n\t\ttransform: translatex(0);\n\n\t\t& ~ ", " {\n\t\t\tmargin-left: 300px;\n\n\t\t\t& .open {\n\t\t\t\tdisplay: none;\n\t\t\t}\n\t\t}\n\t}\n\n\t&:not(:target) ~ ", " .close {\n\t\tdisplay: none;\n\t}\n"], ["\n    padding: 1rem;\n\tbox-sizing: border-box;\n\tbackground: ", ";\n\tposition: fixed;\n\ttop: 0;\n\tleft: 0;\n\theight: 100%;\n\twidth: 300px;\n\ttransform: translatex(-100%);\n\ttransition: transform 0.3s;\n\tbox-shadow: 0 1px 8px 0 ", ";\n\n\t&:target {\n\t\ttransform: translatex(0);\n\n\t\t& ~ ", " {\n\t\t\tmargin-left: 300px;\n\n\t\t\t& .open {\n\t\t\t\tdisplay: none;\n\t\t\t}\n\t\t}\n\t}\n\n\t&:not(:target) ~ ", " .close {\n\t\tdisplay: none;\n\t}\n"])), function (pr) { return pr.bgColor || pr.theme.sidebar.defaults.bgColor; }, function (pr) { return pr.shadowColor || pr.theme.sidebar.defaults.shadowColor; }, Wrapper, Wrapper);
StyledHeader.defaultProps = {
    theme: defaultTheme
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
