var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
var mixin = function (size, Color) {
    switch (size) {
        case "XXS":
            return "\n                height: 15px;\n                width: 15px;\n                border: 1px solid transparent;\n                border-top: 1px solid " + (Color || '#FF5722') + ";\n                &:before{\n                    top: 2px;\n                    right: 2px;\n                    bottom: 2px;\n                    left: 2px;\n                    border: 1px solid transparent;\n                }\n                &:after{\n                    top: 5px;\n                    right: 5px;\n                    bottom: 5px;\n                    left: 5px;\n                    border: 1px solid transparent;\n                }\n           ";
        case "XS":
            return "\n                height: 20px;\n                width: 20px;\n                border: 2px solid transparent;\n                border-top: 2px solid " + (Color || '#FF5722') + ";\n                &:before{\n                    top: 2px;\n                    right: 2px;\n                    bottom: 2px;\n                    left: 2px;\n                    border: 2px solid transparent;\n                }\n                &:after{\n                    top: 5px;\n                    right: 5px;\n                    bottom: 5px;\n                    left: 5px;\n                    border: 2px solid transparent;\n                }\n            ";
        case "S":
            return "\n            height: 40px;\n            width: 40px;\n            border: 4px solid transparent;\n            border-top: 4px solid " + (Color || '#FF5722') + ";\n            &:before{\n                top: 3px;\n                right: 3px;\n                bottom: 3px;\n                left: 3px;\n                border: 4px solid transparent;\n            }\n            &:after{\n                top: 10px;\n                right: 10px;\n                bottom: 10px;\n                left: 10px;\n                border: 4px solid transparent;\n            }\n            ";
        case "M":
            return "\n            height: 60px;\n            width: 60px;\n            border: 5px solid transparent;\n            border-top: 5px solid " + (Color || '#FF5722') + ";\n            &:before{\n                top: 4px;\n                right: 4px;\n                bottom: 4px;\n                left: 4px;\n                border: 5px solid transparent;\n            }\n            &:after{\n                top: 15px;\n                right: 15px;\n                bottom: 15px;\n                left: 15px;\n                border: 5px solid transparent;\n            }\n            ";
        case "L":
            return "\n                border: 6px solid transparent;\n                height: 80px;\n                width: 80px;\n                border-top: 6px solid " + (Color || '#FF5722') + ";\n            &:before{\n                top: 5px;\n                right: 5px;\n                bottom: 5px;\n                left: 5px;\n                border: 6px solid transparent;\n            }\n            &:after{\n                top: 18px;\n                right: 18px;\n                bottom: 18px;\n                left: 18px;\n                border: 6px solid transparent;\n            }\n            ";
        case "XL":
            return "\n            height: 120px;\n            width: 120px;\n            border: 6px solid transparent;\n            border-top: 6px solid " + (Color || '#FF5722') + ";\n            &:before{\n                top: 7px;\n                right: 7px;\n                bottom: 7px;\n                left: 7px;\n                border: 6px solid transparent;\n            }\n            &:after{\n                top: 25px;\n                right: 25px;\n                bottom: 25px;\n                left: 25px;\n                border: 6px solid transparent;\n            }\n            ";
    }
};
export var Loader = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    ", "\n\n    display: block;\n    position: relative;\n    border-radius: 50%;\n    -webkit-animation: spin 2s linear infinite;\n    animation: spin 2s linear infinite;\n\n    &:before,\n    &:after {\n        content: \"\";\n        position: absolute;\n        border-radius: 50%;\n    }\n    &:before {\n        border-top-color:", ";\n        -webkit-animation: spin 3s linear infinite;\n        animation: spin 3.5s linear infinite;\n    }\n    &:after {\n        border-top-color: ", ";\n        -webkit-animation: spin 1.5s linear infinite;\n        animation: spin 1.75s linear infinite;\n    }\n\n    @-webkit-keyframes spin {\n        from {\n            -webkit-transform: rotate(0deg);\n            transform: rotate(0deg);\n        }\n        to {\n            -webkit-transform: rotate(360deg);\n            transform: rotate(360deg);\n        }\n    }\n\n    @keyframes spin {\n        from {\n            -webkit-transform: rotate(0deg);\n            transform: rotate(0deg);\n        }\n        to {\n            -webkit-transform: rotate(360deg);\n            transform: rotate(360deg);\n        }\n    }\n\n"], ["\n    ", "\n\n    display: block;\n    position: relative;\n    border-radius: 50%;\n    -webkit-animation: spin 2s linear infinite;\n    animation: spin 2s linear infinite;\n\n    &:before,\n    &:after {\n        content: \"\";\n        position: absolute;\n        border-radius: 50%;\n    }\n    &:before {\n        border-top-color:", ";\n        -webkit-animation: spin 3s linear infinite;\n        animation: spin 3.5s linear infinite;\n    }\n    &:after {\n        border-top-color: ", ";\n        -webkit-animation: spin 1.5s linear infinite;\n        animation: spin 1.75s linear infinite;\n    }\n\n    @-webkit-keyframes spin {\n        from {\n            -webkit-transform: rotate(0deg);\n            transform: rotate(0deg);\n        }\n        to {\n            -webkit-transform: rotate(360deg);\n            transform: rotate(360deg);\n        }\n    }\n\n    @keyframes spin {\n        from {\n            -webkit-transform: rotate(0deg);\n            transform: rotate(0deg);\n        }\n        to {\n            -webkit-transform: rotate(360deg);\n            transform: rotate(360deg);\n        }\n    }\n\n"])), function (pr) { return mixin(pr.size, pr.Color); }, function (pr) { return pr.innerColor || "#FF9800"; }, function (pr) { return pr.coreColor || "#FFC107"; });
export var LoaderWrapper = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    ", "\n    display: ", ";\n"], ["\n    ", "\n    display: ", ";\n"])), function (pr) { return pr.disabled === true ? 'pointer-events: none;opacity: 0.4;' : ''; }, function (pr) { return pr.visible ? 'inline-block' : 'none'; });
export var StyledWrapper = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    -webkit-box-flex: 0;\n    -ms-flex: 0 0 25%;\n    flex: 0 0 25%;\n    border: 1px solid rgba(255, 255, 255, 0.1);\n    -webkit-box-sizing: border-box;\n    box-sizing: border-box;\n    margin: 0;\n    position: relative;\n    display: -webkit-box;\n    display: -ms-flexbox;\n    display: flex;\n    -webkit-box-pack: center;\n    -ms-flex-pack: center;\n    justify-content: center;\n    -webkit-box-align: center;\n    -ms-flex-align: center;\n    align-items: center;\n    overflow: hidden;\n"], ["\n    -webkit-box-flex: 0;\n    -ms-flex: 0 0 25%;\n    flex: 0 0 25%;\n    border: 1px solid rgba(255, 255, 255, 0.1);\n    -webkit-box-sizing: border-box;\n    box-sizing: border-box;\n    margin: 0;\n    position: relative;\n    display: -webkit-box;\n    display: -ms-flexbox;\n    display: flex;\n    -webkit-box-pack: center;\n    -ms-flex-pack: center;\n    justify-content: center;\n    -webkit-box-align: center;\n    -ms-flex-align: center;\n    align-items: center;\n    overflow: hidden;\n"])));
var templateObject_1, templateObject_2, templateObject_3;
