var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { checkBoxTheme } from "../../theme/core/checkBox";
import { mixin } from '../CheckBox/styled';
export var StyledLi = styled.li(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    width:auto;\n    padding-right:1.5rem;\n"], ["\n    width:auto;\n    padding-right:1.5rem;\n"])));
export var StyledUl = styled.ul(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display:flex;\n    flex-direction:row;\n    margin:0;\n    padding:0;\n    list-style:none;\n    ", "\n"], ["\n    display:flex;\n    flex-direction:row;\n    margin:0;\n    padding:0;\n    list-style:none;\n    ",
    "\n"])), function (pr) {
    return pr.display === 'block' ? "flex-direction:column;" + StyledLi + "{\n        width:100%;\n        }" : '';
});
export var StyledLabel = styled.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    cursor: pointer;\n    padding: 0.8rem 0px;\n    user-select: none;\n    ", ";\n    \n    span{\n        vertical-align:middle;\n        };\n\n    input[type=\"checkbox\"] {\n        vertical-align:middle;\n        border: 1px solid ", ";\n        -webkit-appearance: none;\n        -webkit-transition: box-shadow 200ms;\n        -webkit-border-radius:5px;\n        border-radius:5px;\n        margin-right:0.5rem;\n        \n        &:focus {\n            outline:none;\n        };\n        &:checked {\n            background-color: ", ";\n            &:before {\n                content: '';\n                display: block;\n                border: solid #fff;\n                -webkit-transform: rotate(45deg);\n                transform: rotate(45deg);\n                margin:auto;\n            };\n        };\n\n    };\n    ", ";\n    ", ";\n        \n"], ["\n    cursor: pointer;\n    padding: 0.8rem 0px;\n    user-select: none;\n    ", ";\n    \n    span{\n        vertical-align:middle;\n        };\n\n    input[type=\"checkbox\"] {\n        vertical-align:middle;\n        border: 1px solid ", ";\n        -webkit-appearance: none;\n        -webkit-transition: box-shadow 200ms;\n        -webkit-border-radius:5px;\n        border-radius:5px;\n        margin-right:0.5rem;\n        \n        &:focus {\n            outline:none;\n        };\n        &:checked {\n            background-color: ", ";\n            &:before {\n                content: '';\n                display: block;\n                border: solid #fff;\n                -webkit-transform: rotate(45deg);\n                transform: rotate(45deg);\n                margin:auto;\n            };\n        };\n\n    };\n    ",
    ";\n    ", ";\n        \n"])), function (pr) { return pr.disabled === true ? 'pointer-events: none;opacity: 0.4;' : ''; }, function (pr) { return pr.errorText || pr.hasError ? '#CC0000' : checkBoxTheme.defaults.borderColor; }, function (pr) { return pr.hasError ? '#CC0000' : pr.bgColor || checkBoxTheme.defaults.bgColor; }, function (pr) { return pr.hoverEffect ? "&:hover {\n        " + (pr.labelHoverEffect ? "span{color: " + pr.labelHoverColor + ";}" : '') + "\n        input[type=\"checkbox\"]:checked{\n            background-color: " + (pr.hoverBgColor || checkBoxTheme.defaults.hoverBgColor) + ";\n        };\n        input[type=\"checkbox\"]{\n            border-color:" + checkBoxTheme.defaults.bgColor + ";\n            box-shadow: 0px 4px 19px " + (pr.hoverShadowColor || checkBoxTheme.defaults.shadowColor) + ";\n            }\n        }\n        " :
    ''; }, function (pr) { return pr.size && mixin(pr.size); });
var templateObject_1, templateObject_2, templateObject_3;
